-- MASTER SEED FOR ALL CATEGORIES (255+ QUESTIONS)
-- DELETE FROM questions; -- Optional: Clear existing

INSERT INTO questions (category, question_text, option_a, option_b, option_c, option_d, correct_option) VALUES
('SEGURIDAD_VIAL', '¿Cuál es la principal causa de accidentes?', 'Fallas mecánicas', 'Estado de la vía', 'Exceso de velocidad', 'Clima adverso', 'C'),
('SEGURIDAD_VIAL', '¿Qué hacer ante un herido en un accidente?', 'Moverlo inmediatamente', 'Huir del lugar', 'Proteger la zona y llamar al 123', 'Darle agua', 'C'),
('SEGURIDAD_VIAL', 'El uso del cinturón de seguridad es obligatorio para:', 'Solo el conductor', 'Solo el copiloto', 'Los pasajeros de atrás', 'Todos los ocupantes del vehículo', 'D'),
('SEGURIDAD_VIAL', 'Una señal amarilla con forma de rombo significa:', 'Reglamentaria', 'Preventiva', 'Informativa', 'Transitoria', 'B'),
('SEGURIDAD_VIAL', 'La distancia de seguridad a 60km/h debe ser de al menos:', '10 metros', '20 metros', '30 metros', '5 metros', 'B'),
('SEGURIDAD_VIAL', '¿Cuál es la actitud más peligrosa de un conductor en la vía?', 'La impaciencia y la agresividad', 'Conducir despacio', 'Escuchar música', 'Hablar con el pasajero', 'A'),
('SEGURIDAD_VIAL', 'Si otro conductor le cierra el paso agresivamente, ¿qué debe hacer?', 'Pitar y acelerar', 'Mantener la calma y ceder el paso', 'Bajarse a discutir', 'Seguirlo para reclamarle', 'B'),
('SEGURIDAD_VIAL', 'El "Manejo Defensivo" se basa principalmente en:', 'Tener un vehículo blindado', 'Anticipar errores de otros para evitar accidentes', 'Conducir por el carril izquierdo', 'Frenar en cada esquina', 'B'),
('SEGURIDAD_VIAL', '¿Cómo afecta el consumo de pequeñas cantidades de alcohol a la conducción?', 'No afecta', 'Retarda reflejos y reduce campo visual', 'Mejora la atención', 'Quita el sueño', 'B'),
('SEGURIDAD_VIAL', '¿Qué es el microsueño?', 'Dormir 5 minutos en la berma', 'Pérdida de conciencia por segundos', 'Una técnica de relajación', 'Un fallo del motor', 'B'),
('SEGURIDAD_VIAL', 'Si siente fatiga en un viaje largo, lo correcto es:', 'Subir volumen del radio', 'Tomar energizantes', 'Detenerse y descansar', 'Acelerar', 'C'),
('SEGURIDAD_VIAL', 'En un paso peatonal, ¿quién tiene la prelación?', 'El vehículo', 'El peatón siempre', 'El que llegue primero', 'La moto', 'B'),
('SEGURIDAD_VIAL', 'Distancia lateral mínima al adelantar un ciclista:', '50 cm', '1.5 metros', '3 metros', '10 cm', 'B'),
('SEGURIDAD_VIAL', 'El apoyacabezas sirve para:', 'Descansar', 'Prevenir latigazo cervical', 'Estética', 'Limpieza', 'B'),
('SEGURIDAD_VIAL', 'El "Aquaplaning" se evita:', 'Frenando a fondo', 'Moviendo el volante', 'Reduciendo velocidad y buenas llantas', 'Acelerando', 'C'),
('A2', '¿Cuál es la función principal del casco para un motociclista?', 'Evitar multas', 'Proteger la cabeza de impactos y abrasiones', 'Mejorar la estética', 'Reducir el ruido del viento', 'B'),
('A2', '¿Qué porcentaje del frenado total proporciona el freno delantero en una moto?', '30%', '50%', '70%', '90%', 'C'),
('A2', '¿Cómo debe ir sentado el pasajero en una motocicleta?', 'Sujeto al conductor y pegado a su cuerpo', 'Lo más atrás posible', 'Sentado de lado', 'Sin tocar al conductor', 'A'),
('A2', 'Al conducir con lluvia, ¿qué precaución es primordial?', 'Acelerar para salir rápido de la lluvia', 'Aumentar la distancia de seguridad y reducir la velocidad', 'Usar solo el freno trasero', 'Inclinar más la moto en las curvas', 'B'),
('A2', '¿Qué indica el "Efecto Giroscópico" en una motocicleta?', 'La tendencia a caerse en curvas', 'La estabilidad que mantienen las ruedas al girar a cierta velocidad', 'El humo que sale del escape', 'El ruido del motor', 'B'),
('A2', '¿Cuál es la posición correcta de los pies en los estribos?', 'Con las puntas hacia afuera', 'Apoyando la parte media del pie, paralelos a la moto', 'Solo los talones apoyados', 'Arrastrándolos por el suelo', 'B'),
('A2', '¿Qué es el "Contramanillar"?', 'Girar el manubrio a la derecha para ir a la derecha', 'Presionar levemente el manubrio hacia el lado que se quiere girar a alta velocidad', 'Frenar con el motor', 'Cambiar de carril sin avisar', 'B'),
('A2', '¿Cuándo es obligatorio el uso de la prenda reflectiva?', 'Solo bajo la lluvia', 'De las 18:00 a las 06:00 horas del día siguiente', 'Nunca es obligatoria', 'Solo en carreteras nacionales', 'B'),
('A2', '¿Por qué lado se debe adelantar siempre a otro vehículo?', 'Por la derecha', 'Por la izquierda', 'Por el centro del carril', 'Por la berma', 'B'),
('A2', '¿Qué profundidad mínima debe tener el labrado de las llantas de una moto?', '0.5 mm', '1.0 mm', '1.6 mm', '2.0 mm', 'B'),
('A2', '¿Cuál es el peligro de los "Puntos Ciegos" al conducir moto?', 'Que el sol nos deslumbre', 'Que otros conductores no nos vean en sus espejos', 'Que se dañen los retrovisores', 'No ver los huecos', 'B'),
('A2', 'En un cruce sin señalización, ¿quién tiene la prelación?', 'El que vaya más rápido', 'El vehículo que aparece por el lado derecho', 'La motocicleta por ser más pequeña', 'El vehículo que aparece por el lado izquierdo', 'B'),
('A2', '¿Qué debe revisar antes de iniciar un viaje en moto?', 'Solo el nivel de gasolina', 'Llantas, frenos, luces, cadena y niveles de fluidos', 'Que el casco combine con la moto', 'El retrovisor izquierdo únicamente', 'B'),
('A2', '¿Cómo afecta el viento lateral a la conducción de una moto?', 'No afecta en absoluto', 'Puede desviar la trayectoria de la moto', 'Ayuda a refrigerar el motor', 'Aumenta la velocidad máxima', 'B'),
('A2', '¿Para qué sirve el embrague (clutch) en una moto?', 'Para frenar', 'Para desconectar la fuerza del motor de la rueda trasera y cambiar marchas', 'Para pitar', 'Para encender las luces', 'B'),
('A2', '¿Qué es el "Aquaplaning" en una moto?', 'Lavar la moto con mucha agua', 'Pérdida de tracción al deslizarse sobre una capa de agua', 'Una técnica de acrobacia', 'Cruzar un río profundo', 'B'),
('A2', '¿Cómo se debe tomar una curva correctamente?', 'Frenando a fondo dentro de la curva', 'Reduciendo velocidad antes, mirando la salida y acelerando suavemente', 'Cerrando los ojos', 'Manteniendo el cuerpo totalmente recto e inclinado solo la moto', 'B'),
('A2', '¿Qué documentos son obligatorios para circular en moto?', 'Cédula únicamente', 'Licencia de conducción, SOAT, Tarjeta de Propiedad y Tecnomecánica', 'Solo el carnet de la EPS', 'Fotos de la moto', 'B'),
('A2', '¿Está permitido que una moto circule por las aceras?', 'Solo si hay mucho trancón', 'Nunca, es exclusivo para peatones', 'Solo domiciliarios', 'Si va con el motor apagado', 'B'),
('A2', '¿A qué distancia se debe poner la luz de giro (direccional) antes de un cruce?', 'Justo al girar', 'Con una antelación mínima de 30 metros', '5 metros antes', 'No es necesario en el día', 'B'),
('A2', '¿Cuál es la función del kit de arrastre?', 'Arrastrar la moto cuando se vara', 'Transmitir la potencia del motor a la rueda trasera', 'Sujetar el equipaje', 'Proteger el motor de golpes', 'B'),
('A2', '¿Qué debe hacer si la rueda trasera derrapa?', 'Frenar a fondo con el delantero', 'Dejar de frenar gradualmente y mantener la dirección', 'Acelerar a fondo', 'Saltar de la moto', 'B'),
('A2', '¿Cómo influye la presión de las llantas en la conducción?', 'No tiene ninguna influencia', 'Afecta la estabilidad, el frenado y el consumo de combustible', 'Solo afecta la estética', 'Solo influye si la llanta está pinchada', 'B'),
('A2', '¿Qué indica una señal de tránsito roja y circular con una franja blanca?', 'Permitido el paso', 'Prohibido el ingreso / No entre', 'Pare', 'Zona escolar', 'B'),
('A2', '¿Se puede llevar carga que sobresalga lateralmente en una moto?', 'Sí, hasta 50 cm', 'No, está prohibido por seguridad', 'Solo si está bien amarrada', 'Solo de noche con luces', 'B'),
('A2', '¿Cuál es el límite máximo de velocidad en zona urbana si no hay señales?', '30 km/h', '50 km/h', '60 km/h', '80 km/h', 'B'),
('A2', '¿Qué significa la sigla SOAT?', 'Seguro Obligatorio de Accidentes de Tránsito', 'Sistema de Orden y Acompañamiento Técnico', 'Seguro Operativo de Autos y Transportes', 'Sindicato de Operadores de Alquiler de Transportes', 'A'),
('A2', '¿Cómo debe actuar ante una señal de "PARE"?', 'Disminuir la velocidad y seguir si no viene nadie', 'Detener el vehículo totalmente, observar y luego seguir', 'Pitar para avisar', 'Acelerar para pasar rápido', 'B'),
('A2', '¿Qué es la "Distancia de Reacción"?', 'El tiempo de frenado', 'El espacio que recorre el vehículo desde que el conductor ve el peligro hasta que pisa el freno', 'La distancia entre dos carros', 'Lo que mide el carro', 'B'),
('A2', '¿Por qué es peligroso conducir entre dos vehículos grandes?', 'Porque hacen mucho ruido', 'Por la succión del aire y la falta de visibilidad', 'Porque quitan el sol', 'Porque nos pueden mojar', 'B'),
('A2', '¿Qué debe hacer si se pincha la llanta delantera en movimiento?', 'Frenar a fondo con el frente', 'Sujetar fuerte el manubrio, no frenar bruscamente y orillarse', 'Acelerar', 'Girar el manubrio rápido', 'B'),
('A2', '¿Cuál es la función del aceite de motor?', 'Limpiar el tanque de gasolina', 'Lubricar, refrigerar y limpiar las piezas internas del motor', 'Mejorar el color de la moto', 'Servir de combustible', 'B'),
('A2', '¿Qué significa una línea blanca discontinua en la vía?', 'Prohibido adelantar', 'Permitido adelantar con precaución', 'Solo para buses', 'Paso peatonal', 'B'),
('A2', '¿Cómo se debe transportar a un niño en moto según la ley?', 'Cargado adelante', 'Como parrillero con casco y mayor de 10 años (según municipio)', 'En una maleta', 'No se pueden llevar niños', 'B'),
('A2', '¿Para qué sirve el líquido de frenos?', 'Para lavar los discos', 'Para transmitir la fuerza de la manigueta a las mordazas', 'Para enfriar las llantas', 'No usa líquido', 'B'),
('A2', '¿Qué es el "Punto de Fricción" en el embrague?', 'Cuando la moto se apaga', 'El momento en que el motor empieza a transmitir movimiento a la rueda', 'Cuando el cable se rompe', 'Al frenar a fondo', 'B'),
('A2', '¿Cómo se deben usar las luces en carretera de día?', 'Deben estar siempre encendidas', 'Solo en túneles', 'Solo de noche', 'Solo si hay neblina', 'A'),
('A2', '¿Qué significa la señal "Ceda el Paso"?', 'Detenerse obligatoriamente siempre', 'Disminuir la velocidad y dar prelación a los vehículos que circulan por la otra vía', 'Llevar la iniciativa', 'Pitar para que se quiten', 'B'),
('A2', '¿Qué es la "Seguridad Activa" en una moto?', 'El casco y las rodilleras', 'Los sistemas que ayudan a evitar el accidente (frenos, luces, llantas)', 'El seguro (SOAT)', 'La placa', 'B'),
('A2', '¿Cuál es el riesgo de conducir cansado?', 'Llegar más tarde', 'Pérdida de concentración y aumento del tiempo de reacción', 'Que se acabe el agua', 'Gastar más llantas', 'B'),
('A2', '¿Qué significa una flecha blanca en el piso?', 'Sentido de circulación prohibido', 'Sentido obligatorio de circulación del carril', 'Adorno de la vía', 'Velocidad máxima', 'B'),
('A2', '¿Cómo se debe lubricar la cadena de la moto?', 'Con agua jabonosa', 'Con lubricante específico para cadenas o aceite denso', 'Con gasolina', 'No necesita lubricación', 'B'),
('A2', '¿Qué es la "Hidratación" para un conductor?', 'Lavar la moto', 'Mantener niveles de agua en el cuerpo para evitar fatiga', 'Echar agua al radiador', 'Mojar el piso', 'B'),
('A2', '¿Cuál es la función del exosto o silenciador?', 'Solo para que la moto suene duro', 'Reducir ruidos y emisiones de gases', 'Para calentar los pies', 'Para agarrar la moto', 'B'),
('A2', '¿Qué debe hacer ante un semáforo en amarillo?', 'Acelerar para pasar', 'Detener el vehículo, a menos que ya esté cruzando el cruce', 'Cerrar los ojos', 'Pitar', 'B'),
('A2', '¿Cómo afecta la sobrecarga a la estabilidad de la moto?', 'La hace más estable', 'Dificulta las maniobras y alarga la distancia de frenado', 'No la afecta', 'Mejora el consumo', 'B'),
('A2', '¿Qué hacer si siente que la moto "vibra" mucho al andar?', 'Ignorarlo', 'Revisar balanceo, presión de llantas y estado de rines', 'Subir la velocidad', 'Cambiar de casco', 'B'),
('A2', '¿Qué es la "Pre-inspección"?', 'La revisión tecnomecánica anual', 'La revisión rápida diaria antes de prender el vehículo', 'Mirar si la moto está limpia', 'Revisar multas', 'B'),
('A2', '¿Por qué no se debe usar ropa holgada o bufandas al conducir?', 'Porque se ensucian', 'Porque pueden enredarse en la cadena o ruedas', 'Porque pasan de moda', 'Porque dan calor', 'B'),
('A2', '¿Cuál es la utilidad de los espejos retrovisores?', 'Para verse la cara', 'Para observar el tráfico trasero y lateral sin girar totalmente la cabeza', 'Para que la moto se vea completa', 'Solo se usa el izquierdo', 'B'),
('A2', '¿Qué debe hacer si el motor se apaga repentinamente?', 'Frenar en seco en la mitad de la vía', 'Accionar el embrague, poner direccional y orillarse con el impulso', 'Gritar', 'Pitar persistentemente', 'B'),
('A2', '¿Cómo ayuda el freno motor?', 'A gastar más gasolina', 'A reducir la velocidad usando la compresión del motor al bajar marchas', 'A enfriar los frenos de disco', 'No sirve para nada', 'B'),
('A2', '¿Qué significan las líneas amarillas dobles continuas?', 'Permitido adelantar', 'Prohibido adelantar en ambos sentidos', 'Cruce de peatones', 'Zona de cargue', 'B'),
('A2', '¿Qué es el "Cebreado" en la vía?', 'Pintura en forma de cebra para peatones', 'Líneas oblicuas que indican zonas donde no se debe circular', 'Un tipo de pavimento', 'Manchas de aceite', 'B'),
('A2', '¿Cuál es el ángulo muerto más común?', 'Justo detrás del conductor', 'A los lados, ligeramente atrás, donde no alcanzan a ver los espejos', 'Encima del casco', 'En el tablero de instrumentos', 'B'),
('A2', '¿Qué hacer si un camión grande va a girar?', 'Hacerse a su lado para pasar rápido', 'Darle espacio, ya que necesitan un radio de giro amplio', 'Pegarse a su defensa', 'Pitar para que no gire', 'B'),
('A2', '¿Cómo se identifica una avería en el sistema eléctrico?', 'Por el ruido del motor', 'Fallas en las luces, dificultad al arrancar o testigos en el tablero', 'Por el color del humo', 'Porque se pincha la llanta', 'B'),
('A2', '¿Qué es el "Manejo Preventivo"?', 'Correr mucho', 'Conducir asumiendo que otros pueden cometer errores', 'Andar solo por la derecha', 'No usar frenos', 'B'),
('A2', '¿Cuál es la función de la bujía?', 'Dar luz a la farola', 'Generar la chispa para la combustión del motor', 'Medir el nivel de aceite', 'Bombear gasolina', 'B'),
('A2', '¿Qué significa la luz roja en el tablero con forma de aceitera?', 'Falta de gasolina', 'Baja presión o nivel de aceite del motor', 'El motor está muy caliente', 'La cadena está sucia', 'B'),
('B1', '¿Cuál es la función del sistema de frenos ABS?', 'Frenar más fuerte', 'Evitar que las ruedas se bloqueen durante una frenada de emergencia', 'Hacer que el pedal sea más suave', 'Ahorrar pastillas de freno', 'B'),
('B1', '¿Qué debe hacer si el motor de su vehículo se recalienta?', 'Abrir de inmediato la tapa del radiador', 'Detenerse en un lugar seguro, esperar a que enfríe y revisar niveles', 'Echarle agua fría al motor encendido', 'Seguir conduciendo rápido para que le dé aire', 'B'),
('B1', '¿Cuál es la vigencia del SOAT para vehículos particulares?', '6 meses', '1 año', '2 años', '5 años', 'B'),
('B1', '¿Qué indica el principio de "Seguridad Pasiva"?', 'Evitar el accidente', 'Minimizar las lesiones una vez ocurrido el accidente (ej: airbags)', 'Conducir despacio', 'Usar los espejos', 'B'),
('B1', '¿Cuándo se debe realizar la primera revisión tecnomecánica de un vehículo nuevo particular?', 'Al año de matriculado', 'A los 5 años de matriculado', 'A los 6 años de matriculado', 'A los 2 años de matriculado', 'C'),
('B1', '¿Cuál es el orden correcto para realizar un cambio de carril?', 'Girar, mirar y señalizar', 'Mirar espejos, señalizar y realizar la maniobra si es seguro', 'Señalizar y girar de inmediato', 'Pitar y girar', 'B'),
('B1', '¿Qué significa que un neumático tenga una presión baja?', 'Que dura más', 'Mayor consumo de combustible y riesgo de hidroplaneo', 'Mejor agarre en curvas', 'Que el carro es más veloz', 'B'),
('B1', 'En un cruce con semáforo, si la flecha verde apunta a la derecha y el círculo principal está en rojo:', 'Debe esperar a que todo esté en verde', 'Puede girar a la derecha con precaución', 'Debe pitar para que se quiten', 'No puede girar', 'B'),
('B1', '¿Para qué sirve el testigo de la batería en el tablero?', 'Indica que la radio está encendida', 'Indica un fallo en el sistema de carga (alternador)', 'Indica que las luces están bajas', 'Indica que el carro tiene poca gasolina', 'B'),
('B1', '¿Cuál es la distancia mínima que debe mantener con el vehículo de adelante a 80 km/h?', '10 metros', '30 metros', '50 metros', '5 metros', 'C'),
('B1', '¿Qué debe hacer si se encuentra con una señal de "PARE" en una vía rural?', 'Disminuir la velocidad', 'Detenerse por completo siempre', 'Pasar si no ve polvo de otro carro', 'Pitar y seguir', 'B'),
('B1', '¿Cuál es la función del catalizador?', 'Aumentar la potencia', 'Reducir la toxicidad de los gases de escape', 'Mejorar el sonido', 'Filtrar el aceite', 'B'),
('B1', '¿Cómo se debe actuar ante una frenada de emergencia sin ABS?', 'Pisar el freno a fondo y no soltarlo', 'Presionar y soltar el freno intermitentemente para no bloquear ruedas', 'Usar el freno de mano', 'Apagar el motor', 'B'),
('B1', '¿Qué significa una línea blanca continua en el borde derecho de la vía?', 'Zona de adelanto', 'Demarcación del borde de la calzada / Berma', 'Línea de pare', 'Paso de peatones', 'B'),
('B1', '¿Cuál es el riesgo de llevar objetos sueltos en la bandeja trasera?', 'Que se ensucien', 'Que se conviertan en proyectiles en caso de colisión', 'Que quiten visibilidad únicamente', 'Que se caigan al piso', 'B'),
('B1', '¿Qué profundidad mínima debe tener el labrado de las llantas para un auto?', '0.8 mm', '1.6 mm', '3.0 mm', '5.0 mm', 'B'),
('B1', '¿Cómo influye el peso excesivo en el frenado?', 'Frena igual', 'Aumenta significativamente la distancia de detención', 'Mejora el agarre', 'No afecta si el carro es nuevo', 'B'),
('B1', '¿Qué es el "Manejo Defensivo"?', 'Atacar a otros conductores', 'Evitar accidentes a pesar de las acciones de otros o condiciones adversas', 'Conducir con las luces apagadas', 'No usar los frenos', 'B'),
('B1', '¿Cuál es el propósito del termostato?', 'Medir la gasolina', 'Regular la temperatura del motor permitiendo o no el paso de refrigerante', 'Enfriar el aire acondicionado', 'Calentar los asientos', 'B'),
('B1', '¿Qué debe hacer si las luces directas de otro vehículo lo deslumbran?', 'Poner las luces altas también', 'Mirar hacia la línea blanca de la derecha como referencia', 'Cerrar los ojos', 'Frenar en seco', 'B'),
('B1', '¿Qué significa la señal "Prohibido Girar a la Izquierda"?', 'Que puedo girar si no hay policías', 'Restricción total de giro hacia ese lado', 'Solo prohibido para buses', 'Solo prohibido de noche', 'B'),
('B1', '¿Cuál es la función de los amortiguadores?', 'Sostener el motor', 'Mantener las llantas en contacto con el suelo y absorber irregularidades', 'Hacer que el carro brille', 'Frenar las llantas traseras', 'B'),
('B1', '¿Qué debe hacer al entrar en una glorieta o redoma?', 'Entrar a alta velocidad', 'Ceder el paso a los vehículos que ya circulan dentro de ella', 'Pitar para que le den vía', 'Tener siempre la prioridad', 'B'),
('B1', '¿Cómo se deben usar las luces exploradoras?', 'Todo el tiempo', 'Solo en condiciones de baja visibilidad (niebla o lluvia intensa)', 'Para que el carro se vea mejor', 'En reemplazo de las luces principales', 'B'),
('B1', '¿Cuál es la función del líquido limpiaparabrisas?', 'Enfriar el vidrio', 'Eliminar suciedad y grasa para mantener buena visibilidad', 'Aromatizar el ambiente', 'Lavar el motor', 'B'),
('B1', '¿Qué significa una línea amarilla discontinua en el centro de la vía?', 'Prohibido adelantar', 'Permitido adelantar con precaución en ambos sentidos', 'Solo para motos', 'Vía cerrada', 'B'),
('B1', '¿Cuál es el peligro de conducir con el motor apagado en bajada?', 'Se gasta más gasolina', 'Se pierde la asistencia de frenos y dirección (Hidrovac no funciona)', 'Se ensucian las bujías', 'Ninguno, ahorra energía', 'B'),
('B1', '¿Qué documentos debe portar el conductor de un vehículo?', 'Solo el carnet de la empresa', 'Licencia de conducir, Tarjeta de Propiedad, SOAT y Tecnomecánica', 'Solo fotos de los documentos', 'La factura de compra', 'B'),
('B1', '¿Cómo influye el uso del aire acondicionado en el consumo?', 'No influye', 'Aumenta ligeramente el consumo de combustible', 'Lo disminuye', 'Depende del color del carro', 'B'),
('B1', '¿Cuál es la función del cinturón de seguridad?', 'Evitar multas únicamente', 'Mantener al ocupante en su asiento evitando golpes en caso de impacto', 'Para que el conductor no se mueva en las curvas', 'Comodidad', 'B'),
('B1', '¿Qué es el "Punto de Ebullición" del refrigerante?', 'Cuando el agua se congela', 'La temperatura a la cual el líquido pasa a estado gaseoso', 'Cuando el motor está frío', 'No existe tal punto', 'B'),
('B1', '¿Qué debe hacer si presencia un accidente de tránsito?', 'Seguir de largo', 'Proteger, Avisar y Socorrer (Protocolo PAS)', 'Grabar con el celular y no ayudar', 'Llamar a un mecánico', 'B'),
('B1', '¿Cuál es el límite de velocidad en zonas residenciales?', '20 km/h', '30 km/h', '50 km/h', '60 km/h', 'B'),
('B1', '¿Qué significa la señal preventiva de color amarillo con un símbolo de niños?', 'Zona de juegos', 'Zona escolar próxima', 'Parqueadero de colegios', 'Venta de dulces', 'B'),
('B1', '¿Cuál es la función del aceite de transmisión?', 'Lubricar el motor', 'Lubricar los piñones y engranajes de la caja de cambios', 'Limpiar los vidrios', 'Ayudar al frenado', 'B'),
('B1', '¿Por qué se debe revisar el nivel de líquido de frenos?', 'Porque se evapora rápido', 'Para detectar fugas o desgaste excesivo de las pastillas', 'Para que el pedal esté alto', 'No es necesario revisarlo', 'B'),
('B1', '¿Cómo afecta el alcohol a la visión del conductor?', 'La mejora', 'Produce visión borrosa y reduce la capacidad de juzgar distancias', 'No la afecta', 'Solo afecta de noche', 'B'),
('B1', '¿Qué es la "Visión de Túnel"?', 'Ver bien dentro de túneles', 'Reducción del campo visual lateral por efecto de la velocidad o alcohol', 'Una enfermedad de los ojos', 'Mirar por el retrovisor', 'B'),
('B1', '¿Cuál es la función del alternador?', 'Arrancar el motor', 'Generar energía eléctrica para cargar la batería y alimentar sistemas', 'Girar las llantas', 'Enfriar el habitáculo', 'B'),
('B1', '¿Qué hacer ante una señal de "Ceda el Paso"?', 'Frenar siempre a cero', 'Disminuir la velocidad y dar prelación si hay tráfico en la otra vía', 'Acelerar para ganar el paso', 'No hacer nada', 'B'),
('B1', '¿Cuál es el riesgo de llevar niños en el asiento delantero?', 'Que toquen el radio', 'Lesiones graves por despliegue de airbag o impacto contra el tablero', 'Ninguno si llevan cinturón', 'Que se distraigan', 'B'),
('B1', '¿Cómo se debe comprobar el nivel de aceite del motor?', 'Con el motor encendido', 'Con el motor apagado, en frío y en terreno nivelado', 'En una bajada', 'Después de un viaje largo sin esperar', 'B'),
('B1', '¿Qué significa la señal informativa de color azul?', 'Peligro', 'Servicios, direcciones o información turística', 'Prohibición', 'Obligación', 'B'),
('B1', '¿Cuál es la función de la bomba de agua?', 'Lavar el carro', 'Hacer circular el refrigerante por todo el motor', 'Limpiar el parabrisas', 'Ninguna', 'B'),
('B1', '¿Qué indica el humo azul por el escape?', 'Mucha gasolina', 'Quema de aceite por desgaste de piezas internas', 'Agua en el motor', 'El motor está perfecto', 'B'),
('B1', '¿Qué indica el humo negro por el escape?', 'Mezcla rica (exceso de combustible o filtro de aire sucio)', 'Falta de aceite', 'Bujías nuevas', 'Es normal en todos los carros', 'A'),
('B1', '¿Cuál es la función del embrague o clutch?', 'Frenar el motor', 'Acoplar y desacoplar la potencia del motor a la caja de cambios', 'Acelerar gradualmente', 'No tiene función importante', 'B'),
('B1', '¿Qué debe hacer si falla la dirección asistida?', 'Soltar el volante', 'Sujetar firme, ya que la dirección se pondrá muy dura pero sigue funcionando', 'Apagar el carro', 'Saltar', 'B'),
('B1', '¿Qué significa una doble línea amarilla continua?', 'Zona de parqueo', 'Prohibición de adelantar en ambos sentidos', 'Solo para emergencias', 'Pista de carreras', 'B'),
('B1', '¿Cuál es el uso correcto de las luces altas?', 'En la ciudad siempre', 'En carreteras oscuras cuando no vienen vehículos en sentido contrario', 'Para saludar amigos', 'Para que el de adelante se quite', 'B'),
('B1', '¿Qué es el "Aquaplaning"?', 'Lavar el auto por debajo', 'Deslizamiento incontrolado sobre una capa de agua en la vía', 'Técnica de conducción deportiva', 'Fallo de los frenos en seco', 'B'),
('B1', '¿Cuál es la función de la batería?', 'Mover las llantas', 'Almacenar energía para el arranque y sistemas eléctricos con motor apagado', 'Generar potencia', 'Pesar el carro', 'B'),
('B1', '¿Qué debe hacer antes de abrir la puerta del vehículo al bajar?', 'Abrir rápido', 'Verificar por los espejos que no vengan ciclistas o vehículos', 'Pitar', 'No es necesario mirar', 'B'),
('B1', '¿Cuál es la función del radiador?', 'Calentar el motor', 'Disipar el calor del refrigerante mediante el paso del aire', 'Almacenar aceite', 'No tiene función', 'B'),
('B1', '¿Qué indica el testigo de la aceitera roja?', 'Falta de gasolina', 'Presión de aceite insuficiente (peligro para el motor)', 'Cambio de aceite próximo', 'Aceite de buena calidad', 'B'),
('B1', '¿Cuál es la función de los fusibles?', 'Ahorrar energía', 'Proteger el sistema eléctrico de sobrecargas fundiéndose primero', 'Gastar batería', 'Decoración', 'B'),
('B1', '¿Qué significa la señal de flecha curva con flecha pequeña tachada?', 'Prohibido girar a la derecha', 'Prohibido girar en U', 'Prohibido adelantar', 'Vía sin salida', 'B'),
('B1', '¿Cuál es la importancia de la alineación y balanceo?', 'Solo estética', 'Evitar vibraciones, desgaste irregular de llantas y mejorar estabilidad', 'Para que el carro corra más', 'Para que gaste más aceite', 'B'),
('B1', '¿Qué indican las luces blancas traseras?', 'Frenado', 'Reversa / Marcha atrás', 'Direccionales', 'Luces de parqueo', 'B'),
('B1', '¿Qué hacer si un neumático estalla mientras conduce?', 'Frenar fuerte de inmediato', 'Sujetar firme el volante, dejar de acelerar y frenar muy suavemente al final', 'Girar el volante al lado opuesto', 'Soltar el volante', 'B'),
('C1', '¿Qué tipo de vehículos contempla la categoría de licencia C1?', 'Vehículos de carga pesada', 'Automóviles, camperos, camionetas y microbuses de servicio público', 'Solo motocicletas', 'Tractocamiones', 'B'),
('C1', '¿Cuál es la vigencia de la licencia de conducción para servicio público en conductores menores de 60 años?', '6 meses', '1 año', '3 años', '10 años', 'C'),
('C1', '¿Qué es la Tarjeta de Operación?', 'Un permiso para parquear', 'Documento que autoriza al vehículo para prestar servicio público', 'Un carnet de conductor', 'La tarjeta de identidad', 'B'),
('C1', '¿Cuál es la frecuencia de la revisión tecnomecánica para vehículos de servicio público?', 'Cada 2 años', 'Anual (desde el primer año de matrícula)', 'Cada 5 años', 'No necesitan revisión', 'B'),
('C1', '¿Qué indica el seguro de Responsabilidad Civil Contractual?', 'Cubre daños al vehículo únicamente', 'Cubre a los pasajeros frente a accidentes durante la prestación del servicio', 'Cubre solo lesiones al conductor', 'Es opcional', 'B'),
('C1', '¿Cuál es la capacidad máxima de pasajeros para un microbús según su configuración estándar?', '5 pasajeros', 'Hasta 19 pasajeros', '50 pasajeros', 'Indefinida', 'B'),
('C1', '¿Qué debe hacer un conductor de servicio público ante un pasajero con discapacidad?', 'No recogerlo', 'Prestar ayuda y facilitar su ingreso y acomodación con prioridad', 'Cobrarle más', 'Pedir que espere otro vehículo', 'B'),
('C1', '¿Está permitido fumar dentro de un vehículo de transporte público?', 'Si el pasajero lo solicita', 'No, está prohibido por ley para conductor y pasajeros', 'Solo el conductor', 'Si las ventanas están abiertas', 'B'),
('C1', '¿Cuál es el límite de velocidad en carreteras nacionales para servicio público?', '120 km/h', '80 km/h', '100 km/h', '60 km/h', 'B'),
('C1', '¿Qué es el "Plan Estratégico de Seguridad Vial" (PESV)?', 'Una multa', 'Un instrumento de planeación para reducir accidentes en empresas de transporte', 'Un tipo de llanta', 'El mapa de rutas', 'B'),
('C1', '¿Para qué sirve el extintor de incendios en el equipo de carretera?', 'Solo para cumplir la norma', 'Para controlar conatos de incendio en el vehículo o cercanías', 'Como adorno', 'Para enfriar el motor', 'B'),
('C1', '¿Qué indica el color naranja en las placas de un vehículo?', 'Uso diplomático', 'No existe tal placa', 'Transporte escolar únicamente (en algunos contextos)', 'Es un color descriptivo no usado en placas estándar', 'C'),
('C1', '¿Qué documento garantiza la seguridad de terceros no transportados en un accidente?', 'Tarjeta de operación', 'Seguro de Responsabilidad Civil Extracontractual', 'Cédula', 'Pase', 'B'),
('C1', '¿Cómo debe actuar si un pasajero olvida un objeto en su vehículo?', 'Quedarse con él', 'Reportarlo y entregarlo en el centro de acopio o empresa', 'Botarlo', 'Venderlo', 'B'),
('C1', '¿Qué es el "Transporte Especial"?', 'Transporte de carga peligrosa', 'Transporte de grupos específicos (escolar, empresarial, turismo)', 'Taxis amarillos', 'Ambulancias', 'B'),
('C1', '¿Cuál es la función principal de los radares de velocidad?', 'Decoración de la vía', 'Controlar que los conductores no excedan los límites para prevenir accidentes', 'Tomar fotos de los paisajes', 'Aumentar el tráfico', 'B'),
('C1', '¿Qué hacer si un pasajero está en estado de embriaguez agresiva?', 'Pelear con él', 'Solicitar apoyo policial y evitar confrontaciones directas', 'Abandonarlo en la vía vacía', 'Llevarlo a su casa gratis', 'B'),
('C1', '¿Qué indica una señal informativa con un teléfono?', 'Prohibido usar celular', 'Presencia de un teléfono público o socorro próximo', 'Zona de cargue', 'Museo', 'B'),
('C1', '¿Cuál es la sanción por prestar servicio público en vehículo particular?', 'Una advertencia', 'Multa e inmovilización del vehículo', 'No hay sanción', 'Pagar el doble de peajes', 'B'),
('C1', '¿Qué es la "Capacidad Transportadora"?', 'La fuerza del motor', 'Número máximo de vehículos que una empresa puede tener vinculados', 'El peso de la carga', 'La velocidad máxima', 'B'),
('C1', '¿Para qué sirve el diagrama de rutas?', 'Para decorar el bus', 'Indicar el recorrido autorizado y paradas permitidas', 'Para que el pasajero lea', 'No es obligatorio', 'B'),
('C1', '¿Qué debe revisar en el botiquín de primeros auxilios?', 'Que tenga comida', 'Fechas de vencimiento y completitud de los elementos básicos', 'Que sea de color rojo', 'Nada, se compra una vez', 'B'),
('C1', '¿Cuál es el propósito del regulador de velocidad en algunos vehículos?', 'Aumentar la potencia', 'Limitar técnicamente la velocidad máxima para mayor seguridad', 'Ahorrar llantas', 'Pitar más fuerte', 'B'),
('C1', '¿Cómo debe ir identificado el conductor de servicio público?', 'Con ropa de calle común', 'Con carnet de identificación visible o según reglamento de la empresa', 'Con una gorra', 'No necesita identificación', 'B'),
('C1', '¿Qué es el "Manifiesto de Carga" (aplicable a mixtos)?', 'Una carta de amor', 'Documento que detalla la carga, origen, destino y flete', 'Recibo de gasolina', 'Lista de pasajeros', 'B'),
('C1', '¿Cuál es el riesgo de llevar pasajeros de pie en vehículos no autorizados?', 'Se cansan más', 'Inestabilidad del vehículo y riesgo de fatalidad en frenazos o choques', 'Que no paguen', 'Ninguno', 'B'),
('C1', '¿Qué significa la señal con un bus y un reloj?', 'Bus rápido', 'Paradero con horario establecido o terminal', 'Venta de relojes', 'Zona de descanso', 'B'),
('C1', '¿A quién debe reportar un fallo mecánico durante la ruta?', 'A los pasajeros solamente', 'A la central de despacho o empresa y seguridad vial', 'A nadie, tratar de arreglarlo solo', 'Al seguro después de 2 días', 'B'),
('C1', '¿Qué es la "Ética del Conductor"?', 'Cobrar lo que quiera', 'Respeto a las normas, a los pasajeros y compromiso con la vida', 'Saber arreglar el motor', 'Ganar siempre la vía', 'B'),
('C1', '¿Cuál es el uso de los martillos de seguridad en microbuses?', 'Para arreglar el motor', 'Romper vidrios en caso de emergencia/volcamiento para evacuación', 'Para defensa personal', 'Para ajustar las sillas', 'B'),
('C1', '¿Qué indica una luz de advertencia de puertas abiertas?', 'Que el carro está aireado', 'Peligro inminente para los pasajeros, debe detenerse y cerrar', 'Error del sensor sin importancia', 'Que puede subir gente', 'B'),
('C1', '¿Cuál es la función del tacógrafo o sistemas de GPS?', 'Mirar películas', 'Registrar tiempos de marcha, velocidades y ubicación para control', 'Ocupar espacio', 'Medir la música', 'B'),
('C1', '¿Qué es el "Manual de Funciones"?', 'Un libro sobre mecánica', 'Documento que define responsabilidades y procedimientos del conductor', 'Un catálogo de bus', 'No existe', 'B'),
('C1', '¿Cómo debe manejar el dinero de los pasajes?', 'Dejándolo regado', 'De forma organizada en gabas o sistemas electrónicos autorizados', 'En los bolsillos mezclado', 'Entregarlo todo a los pasajeros', 'B'),
('C1', '¿Qué es el "Servicio de Lujo" en taxis?', 'Taxi con música alta', 'Servicio con niveles de calidad, seguridad y tarifas diferenciadas', 'Taxis viejos pero limpios', 'Servicio gratuito', 'B'),
('C1', '¿Cuál es la función de la alarma de reversa?', 'Pitar a los amigos', 'Advertir a peatones y otros vehículos que el vehículo retrocederá', 'Para que el conductor no se duerma', 'Decoración acústica', 'B'),
('C1', '¿Qué hacer si el vehículo emite ruidos extraños en los frenos?', 'Poner más música', 'Suspender el servicio de inmediato y revisar en taller especializado', 'Seguir hasta que se acabe el turno', 'Echarles agua', 'B'),
('C1', '¿Qué busca la "Economía en la Conducción"?', 'Andar muy despacio siempre', 'Optimizar el combustible y reducir emisiones mediante técnicas suaves', 'No prender las luces', 'Usar llantas lisas', 'B'),
('C1', '¿Cuál es la importancia de la higiene personal del conductor?', 'Ninguna', 'Imagen institucional de la empresa y respeto al usuario', 'Para que el carro no huela a feo', 'Solo los domingos', 'B'),
('C1', '¿Qué hacer ante una falla en el sistema de aire acondicionado?', 'Cancelar el viaje', 'Informar y ventilar el vehículo de forma manual si es posible', 'Cobrar menos', 'Gritar', 'B'),
('C1', '¿Cuál es el riesgo de la fatiga visual?', 'Ver mejor de noche', 'Pérdida de nitidez y retraso en detección de obstáculos', 'Que le lloren los ojos únicamente', 'Ninguno', 'B'),
('C1', '¿Qué significa la señal de "Prohibido el cargue y descargue"?', 'Que solo buses pueden parar', 'Restricción de manipular mercancía en esa zona y horario', 'Zona de juegos', 'Zona de espera', 'B'),
('C1', '¿Cuál es la función del diferencial?', 'Hacer que el carro sea diferente', 'Permitir que las ruedas motrices giren a distinta velocidad en curvas', 'Frenar el motor', 'Ahorrar aceite', 'B'),
('C1', '¿Qué documentos del vehículo deben estar visibles al pasajero?', 'Ninguno', 'Tarjeta de control (donde se vea tarifa, conductor y empresa)', 'Factura de gasolina', 'Cédula del dueño', 'B'),
('C1', '¿Cuál es el efecto de la lluvia en la distancia de frenado?', 'La reduce', 'La aumenta al menos al doble por la falta de adherencia', 'Sigue siendo la misma', 'Mejora el frenado', 'B'),
('C1', '¿Qué significa "Prelación de Vía"?', 'Echar el carro', 'Derecho preferente de paso sobre otros usuarios de la vía', 'La vía más bonita', 'No existe tal concepto', 'B'),
('C1', '¿Cuál es el riesgo de usar el celular con manos libres?', 'Se descarga el equipo', 'Distracción cognitiva (atención dividida)', 'Que se le caiga', 'Ninguno', 'B'),
('C1', '¿Cómo debe actuar si un pasajero sufre un ataque de salud?', 'Bajarlo en la siguiente esquina', 'Contactar emergencias, auxiliar según capacidad y llevar al centro de salud más cercano', 'Seguir la ruta normal', 'Asustarse y correr', 'B'),
('C1', '¿Qué significa la señal de "Ciclistas en la vía"?', 'Vía para ciclas únicamente', 'Prevención por presencia frecuente de ciclistas, extremar cuidado', 'Venta de bicicletas', 'Prohibido bicicletas', 'B'),
('C1', '¿Cuál es la función de la suspensión?', 'Hacer el carro más alto', 'Garantizar confort y estabilidad absorbiendo impactos y manteniendo contacto', 'Para que no suene el motor', 'Sujetar el chasis', 'B'),
('C1', '¿Qué es el "Tiempo de Percepción"?', 'Lo que dura el viaje', 'Tiempo desde que aparece el estímulo hasta que el cerebro lo reconoce', 'El tiempo de espera de un cliente', 'Un reloj', 'B'),
('C1', '¿Por qué es importante el aseo diario del vehículo?', 'Para que pese menos', 'Salud pública, confort del usuario y buena presentación del servicio', 'Solo si va a llover', 'No es importante', 'B'),
('C1', '¿Qué significa una flecha de giro blanca sobre fondo verde?', 'Peligro', 'Ruta de evacuación o salida de emergencia', 'Gire si quiere', 'Dirección de la empresa', 'B'),
('C1', '¿Cuál es la función de la barra estabilizadora?', 'Ahorrar combustible', 'Reducir la inclinación de la carrocería en las curvas', 'Para amarrar el carro', 'No tiene función', 'B'),
('C1', '¿Qué hacer si siente el pedal del freno "esponjoso"?', 'Bombear rápido', 'Revisar aire en el sistema o nivel bajo de líquido de inmediato', 'No importa si frena', 'Es normal en calor', 'B'),
('C1', '¿Cómo afecta la alta temperatura exterior al vehículo?', 'Mejora el enfriamiento', 'Aumenta riesgo de recalentamiento y fatiga del conductor', 'No afecta', 'Hace que ande más', 'B'),
('C1', '¿Qué significa la señal informativa "Terminal de Transporte"?', 'Cementerio de buses', 'Lugar de llegada, salida y despacho de vehículos de servicio público', 'Final de la vía', 'Museo de transporte', 'B'),
('C1', '¿Cuál es la importancia de los tiempos de descanso?', 'Para ver más TV', 'Prevenir la fatiga, el estrés y garantizar una conducción alerta y segura', 'Gastar más tiempo', 'Ninguna', 'B'),
('C1', '¿Qué es el "Servicio Mixto"?', 'Transporte de hombres y mujeres solamente', 'Transporte simultáneo de pasajeros y carga lícita debidamente separada', 'Bus que parece taxi', 'Bicicleta con motor', 'B'),
('C1', '¿Qué indica el testigo de "Check Engine" naranja?', 'Motor apagado', 'Fallo detectado por la computadora en algún sistema del motor', 'Cambio de filtro', 'Todo está bien', 'B'),
('C2', '¿Qué tipo de vehículos contempla la categoría de licencia C2?', 'Solo taxis', 'Camiones rígidos, busetas y buses de servicio público', 'Tractocamiones de 3 ejes', 'Motocicletas de alto cilindraje', 'B'),
('C2', '¿Cuál es la función principal del freno de aire?', 'Enfriar las llantas', 'Utilizar aire comprimido para accionar las zapatas o pastillas de freno en vehículos pesados', 'Limpiar el motor', 'Pitar más fuerte', 'B'),
('C2', '¿Qué es el "Punto de Inestabilidad" en un vehículo de carga?', 'Cuando se acaba la gasolina', 'Límite donde la carga se desplaza o el vehículo puede volcar por exceso de peso o velocidad en curva', 'Cuando el conductor está cansado', 'Al encender las luces', 'B'),
('C2', '¿Cuál es la altura máxima permitida (estándar) para la mayoría de vehículos en Colombia?', '2.50 metros', '4.40 metros', '3.00 metros', '5.00 metros', 'B'),
('C2', '¿Qué debe revisar en el manómetro de los tanques de aire?', 'La temperatura del agua', 'Que la presión se encuentre en el rango operativo (aprox 100-120 PSI)', 'El nivel de aceite', 'La hora', 'B'),
('C2', '¿Para qué sirve el "Gobernador" en el sistema de aire?', 'Para mandar en el bus', 'Controlar el ciclo de carga y descarga del compresor de aire', 'Medir la velocidad', 'Frenar la rueda delantera', 'B'),
('C2', '¿Qué es el "Ángulo Muerto" en un camión?', 'Un golpe en la carrocería', 'Zonas alrededor del vehículo donde el conductor no tiene visibilidad directa o por espejos', 'La parte trasera del camión únicamente', 'Debajo del motor', 'B'),
('C2', '¿Cómo debe realizarse el descenso de una pendiente prolongada y fuerte?', 'En neutro para ahorrar combustible', 'En el mismo cambio (marcha) con el que subiría la pendiente, usando freno motor', 'Frenando todo el tiempo suavemente con el pedal', 'Apagando el motor', 'B'),
('C2', '¿Qué indica el fenómeno de "Fading" en los frenos?', 'Que están nuevos', 'Pérdida de eficacia por sobrecalentamiento de las bandas o pastillas', 'Que tienen mucha agua', 'Que el aire está muy frío', 'B'),
('C2', '¿Cuál es la función del freno de parqueo (Spring Brake) en vehículos pesados?', 'Frenar en los semáforos', 'Mantener el vehículo frenado mediante resortes potentes cuando no hay presión de aire', 'Ayudar al arranque', 'Es opcional', 'B'),
('C2', '¿Qué es la "Capacidad de Carga Útil"?', 'El peso total del camión vacío', 'El peso máximo de mercancía o pasajeros que el vehículo puede transportar legalmente', 'Lo que pesa el conductor', 'La cantidad de gasolina', 'B'),
('C2', '¿Cómo afecta un centro de gravedad alto a la estabilidad?', 'Lo hace más estable', 'Aumenta el riesgo de volcamiento en curvas y maniobras bruscas', 'No afecta en nada', 'Ayuda a correr más', 'B'),
('C2', '¿Para qué sirven las "Cintas Retrorreflectivas" en vehículos grandes?', 'Para que se vean bonitos', 'Hacer el vehículo visible de noche o en baja visibilidad desde distancias seguras', 'Tapar golpes', 'Publicidad', 'B'),
('C2', '¿Qué debe hacer si escucha silbidos constantes en el sistema de frenos de aire?', 'Subir el volumen del radio', 'Detenerse y revisar fugas en mangueras o válvulas de inmediato', 'Echarles jabón', 'Es normal', 'B'),
('C2', '¿Cuál es la función del secador de aire?', 'Secar el vehículo por fuera', 'Eliminar la humedad y contaminantes del aire comprimido para proteger válvulas', 'Calentar la cabina', 'Ninguna', 'B'),
('C2', '¿Qué es el "Radio de Giro"?', 'El tamaño del volante', 'Espacio mínimo necesario para que el vehículo realice un giro completo', 'La estación de radio del bus', 'La distancia de los ejes', 'B'),
('C2', '¿Por qué se debe drenar los tanques de aire diariamente?', 'Para que pesen menos', 'Para extraer el agua y aceite acumulado que puede dañar el sistema', 'Por estética', 'No es necesario', 'B'),
('C2', '¿Qué indica una señal de tránsito circular blanca con borde rojo y un número seguido de "t"?', 'Velocidad máxima', 'Peso máximo permitido por eje o total en toneladas', 'Distancia a la ciudad', 'Número de pasajeros', 'B'),
('C2', '¿Cómo influye la presión de las llantas traseras (duales/pacha) en la carga?', 'Deben estar siempre a 30 PSI', 'Deben tener la presión recomendada para soportar el peso y evitar recalentamiento', 'Una más inflada que la otra', 'No importa', 'B'),
('C2', '¿Qué es el "Efecto Tijera" (Jackknife)?', 'Cortar cables con tijeras', 'Pérdida de control donde la cabina y el remolque se doblan entre sí (más común en C3, pero riesgo en articulados)', 'Un tipo de suspensión', 'Abrir las puertas modo tijera', 'B'),
('C2', '¿Para qué sirve el Intercooler?', 'Enfriar el aire que entra al turbo para mejorar la combustión', 'Enfriar el aceite', 'Calentar la cabina', 'No tiene uso', 'A'),
('C2', '¿Cómo debe ser la sujeción de la carga?', 'Con cuerdas delgadas', 'Usando elementos certificados (lingas, cadenas) según el peso y tipo de carga', 'Solo puesta encima', 'Con cinta pegaste', 'B'),
('C2', '¿Qué indica el humo blanco constante por el escape en un motor diesel?', 'Combustión perfecta', 'Presencia de agua en el cilindro o problemas de inyección/enfriamiento', 'Falta de aire', 'Es vapor normal siempre', 'B'),
('C2', '¿Cuál es la función del limitador de velocidad en camiones?', 'Poder correr más', 'Garantizar que no exceda los límites legales y mejorar seguridad y consumo', 'Frenar en seco', 'No tiene función', 'B'),
('C2', '¿Qué hacer si un neumático de la pacha (trasero dual) está pinchado?', 'Seguir así, total hay otro', 'Cambiarlo de inmediato, el otro neumático se sobrecarga y puede estallar', 'Quitar los dos', 'Ignorarlo hasta que llegue al destino', 'B'),
('C2', '¿Qué es la "Quinta Rueda" (en vehículos compatibles)?', 'La llanta de repuesto', 'El dispositivo de acoplamiento entre el cabezote y el semirremolque', 'Un volante extra', 'Una técnica de parqueo', 'B'),
('C2', '¿Cuál es la importancia de la revisión de luces en un bus/camión?', 'Ninguna', 'Vital para ser visto por otros conductores debido al gran tamaño del vehículo', 'Solo para ver el tablero', 'No es obligatoria', 'B'),
('C2', '¿Qué hacer ante una señal restrictiva de "Altura Máxima"?', 'Pasar despacio para ver si pega', 'No pasar si la altura del vehículo más la carga superan lo indicado', 'Acelerar', 'Desinflar las llantas', 'B'),
('C2', '¿Cuál es la función del tacómetro?', 'Medir la velocidad en km/h', 'Indicar las revoluciones por minuto (RPM) del motor para cambios eficientes', 'Medir el tiempo del viaje', 'Indicar la presión de aceite', 'B'),
('C2', '¿Qué es el "Retardador" (Retarder)?', 'Un acelerador', 'Sistema de freno auxiliar (hidráulico o eléctrico) para descenso de pendientes', 'Una luz de freno', 'Alguien que llega tarde', 'B'),
('C2', '¿Por qué los vehículos pesados deben tomar las curvas más abiertas?', 'Por gusto', 'Para compensar el desplazamiento de las ruedas traseras y no invadir carriles', 'Para que los vean mejor', 'No es necesario', 'B'),
('C2', '¿Qué indica el testigo de baja presión de aire (luz roja o zumbador)?', 'Frenos listos', 'Peligro: Presión insuficiente para garantizar el frenado seguro', 'Puerta abierta', 'Luz de cortesía', 'B'),
('C2', '¿Cuál es el uso de las cuñas o tacos de seguridad?', 'Como apoyo del gato únicamente', 'Asegurar el vehículo cuando se estaciona en pendientes para evitar desplazamientos', 'Lavar las llantas', 'No se usan en camiones', 'B'),
('C2', '¿Qué es el "Peso Bruto Vehicular"?', 'El peso de la carga sola', 'Suma del peso del vehículo vacío más la carga y ocupantes', 'El peso del conductor', 'El peso del motor', 'B'),
('C2', '¿A qué distancia se debe colocar los triángulos de seguridad en carretera en caso de vara?', 'A 1 metro', 'Entre 50 y 100 metros del vehículo', 'Pegados a la defensa', 'No se usan', 'B'),
('C2', '¿Cuál es la función del lubricante en la caja de cambios?', 'Enfriar el habitáculo', 'Reducir la fricción y el desgaste de los engranajes', 'Mejorar la música', 'No lleva lubricante', 'B'),
('C2', '¿Qué significa la señal "Prohibido el paso de vehículos pesados"?', 'Que solo buses pueden pasar', 'Restricción total para vehículos de carga superior al peso indicado', 'Zona de descargue', 'Vía peligrosa', 'B'),
('C2', '¿Cómo afecta la lluvia a la visibilidad en espejos grandes?', 'La mejora', 'La reduce drásticamente, requiere uso de desempañadores o mayor atención', 'No afecta', 'Se ven más grandes', 'B'),
('C2', '¿Cuál es la importancia del "Ralentí" (marcha mínima)?', 'Gastara gasolina por gusto', 'Mantener el motor funcionando a bajas RPM para lubricación e inicio de marcha', 'Solo para calentar el café', 'Hacer ruido', 'B'),
('C2', '¿Qué es el "Acompañante" o ayudante en vehículos de carga?', 'Alguien que habla mucho', 'Persona que apoya en maniobras difíciles y aseguramiento de carga', 'Es obligatorio tener dos', 'No existe tal figura', 'B'),
('C2', '¿Qué significa la luz verde en el tablero con forma de faroles?', 'Motor frío', 'Luces de posición o corto alcance encendidas', 'Todo está bien', 'Luz de reversa', 'B'),
('C2', '¿Cuál es la función de la suspensión de aire (fuelle)?', 'Inflar las llantas', 'Proveer un viaje más suave y ajustar la altura del vehículo según la carga', 'Frenar la llanta', 'Secar el piso', 'B'),
('C2', '¿Qué hacer si nota una mancha de aceite grande debajo del motor?', 'Limpiarla y seguir', 'Revisar niveles e identificar la fuga antes de iniciar marcha para evitar daños', 'Echarle agua', 'Pasar por encima', 'B'),
('C2', '¿Qué es la "Conducción Económica"?', 'No pagar peajes', 'Técnica para minimizar el desgaste del vehículo y el consumo de combustible', 'Usar llantas baratas', 'Andar sin luces', 'B'),
('C2', '¿Cuál es el peligro de los neumáticos reencauchados en el eje delantero?', 'Ninguno', 'Riesgo de desprendimiento o estallido, comprometiendo la dirección', 'Son prohibidos por ley en todos los ejes', 'Duran más', 'B'),
('C2', '¿Qué es el "Voladizo" en un vehículo de carga?', 'El techo', 'La parte del vehículo que sobresale de los ejes delantero o trasero', 'Una técnica de vuelo', 'El volante', 'B'),
('C2', '¿Cuál es la función del silenciador?', 'Para que no los oiga la policía', 'Reducir el ruido de los gases de escape', 'Aumentar la velocidad', 'Decorativo', 'B'),
('C2', '¿Qué indica la señal informativa verde con un camión?', 'Zona de carga protegida', 'Paradero o terminal de transporte de carga / Pesaje', 'Venta de camiones', 'Prohibido camiones', 'B'),
('C2', '¿Por qué es vital verificar el ajuste de los pernos de las ruedas?', 'Para que no suenen', 'Evitar que la rueda se suelte en movimiento por vibración o carga', 'Por estética del rin', 'No es importante', 'B'),
('C2', '¿Cuál es el riesgo de la "Distracción" en conductores de largo recorrido?', 'Llegar más tarde', 'Aumento del riesgo de accidentes catastróficos por fatiga o monotonía', 'Que se le pierda el camino únicamente', 'Ninguno', 'B'),
('C2', '¿Qué significa la sigla RUNT?', 'Registro Único Nacional de Tránsito', 'Red Universal de Transportes', 'Revisiones Únicas para Nuevas Tecnologías', 'Ruta Unificada Nacional', 'A'),
('C2', '¿Cuál es la función de las válvulas de alivio en el sistema de aire?', 'Pitar', 'Liberar exceso de presión para evitar daños en los tanques y tuberías', 'Inflar balones', 'Dar aire al conductor', 'B'),
('C2', '¿Qué hacer ante una falla total de frenos en bajada?', 'Gritar y saltar', 'Usar cambios bajos, buscar rampa de frenado o frotar contra barrera lateral', 'Apagar el motor de inmediato', 'Cerrar los ojos', 'B'),
('C2', '¿Qué es el "Cubicaje"?', 'Capacidad de gasolina', 'Volumen interno disponible para carga en el furgón o platón', 'El tamaño de las llantas', 'La altura del conductor', 'B'),
('C2', '¿Cuál es la función del turbo cargador?', 'Hacer que el bus suene mejor', 'Inyectar más aire al motor para aumentar la potencia y eficiencia', 'Frenar la caja', 'Girar las llantas', 'B'),
('C2', '¿Por qué no se debe sobrepasar la capacidad de carga?', 'Porque se gasta la pintura', 'Daño de suspensión, chasis, frenos ineficientes y riesgo de accidentes', 'No pasa nada si es poquito', 'Para que el motor corra más', 'B'),
('C2', '¿Qué significa la señal de "Pendiente Fuerte"?', 'Zona de descanso', 'Advertencia de bajada o subida pronunciada, requiere precaución y cambios bajos', 'Pista de carreras', 'Vía sin salida', 'B'),
('C2', '¿Cuál es la importancia del "Mantenimiento Preventivo"?', 'Solo para cuando se dañe', 'Anticiparse a las fallas mediante inspecciones periódicas para garantizar seguridad', 'Para que el carro esté limpio', 'Gastar dinero', 'B'),
('C2', '¿Qué es la "Bitácora de Viaje"?', 'Un mapa', 'Registro de tiempos, descansos, novedades y eventos durante el recorrido', 'Libro de cuentos', 'Factura de carga', 'B'),
('C2', '¿Qué indica el testigo de temperatura del motor en la zona roja?', 'El aire acondicionado está full', 'Recalentamiento severo del motor, debe apagarse de inmediato', 'El motor está caliente y listo para correr', 'Error de tablero', 'B');